### ISSUE TITLE
"IV must be 16 bytes long"

### ISSUE THREAD

**Issue by iii235** [Mik317/PyBotnet#2]
The Server won't start, this is the output I get:Traceback (most recent call last):
  File "Server.py", line 16, in <module>
    PASS = base64.b64encode(AES.new(KEY, AES.MODE_CBC).encrypt(KEY).hex().encode()).decode()
  File "/usr/lib/python3/dist-packages/Crypto/Cipher/AES.py", line 94, in new
    return AESCipher(key, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/Crypto/Cipher/AES.py", line 59, in __init__
    blockalgo.BlockAlgo.__init__(self, _AES, key, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/Crypto/Cipher/blockalgo.py", line 141, in __init__
    self._cipher = factory.new(key, *args, **kwargs)
ValueError: IV must be 16 bytes long

**Comment by FreezyEx** [comment]
I fixed it removing the encoding part. Just set a normal string in PASS
