### ISSUE TITLE
traceback error

### ISSUE THREAD

**Issue by abhaythakur71181** [Mik317/PyBotnet#7]
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cherrypy/lib/lockfile.py", line 69, in __init__
    self.fp = open(path, 'r+')
FileNotFoundError: [Errno 2] No such file or directory: '/home/kali/Desktop/PyBotnet/data/sessions\\/session-79a74bcaed17be0b4698eb8ebb1f1d1c976bffc7.lock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cherrypy/_cprequest.py", line 667, in respond
    self.hooks.run('before_handler')
  File "/usr/lib/python3/dist-packages/cherrypy/_cprequest.py", line 114, in run
    raise exc
  File "/usr/lib/python3/dist-packages/cherrypy/_cprequest.py", line 104, in run
    hook()
  File "/usr/lib/python3/dist-packages/cherrypy/_cprequest.py", line 63, in __call__
    return self.callback(**self.kwargs)
  File "/usr/lib/python3/dist-packages/cherrypy/_cptools.py", line 287, in _lock_session
    cherrypy.serving.session.acquire_lock()
  File "/usr/lib/python3/dist-packages/cherrypy/lib/sessions.py", line 542, in acquire_lock
    self.lock = lockfile.LockFile(path)
  File "/usr/lib/python3/dist-packages/cherrypy/lib/lockfile.py", line 75, in __init__
    self.fp = open(path, 'a+')
FileNotFoundError: [Errno 2] No such file or directory: '/home/kali/Desktop/PyBotnet/data/sessions\\/session-79a74bcaed17be0b4698eb8ebb1f1d1c976bffc7.lock'

**Comment by cloudcant** [comment]
getting this same error , i let you know if i find a fix

**Comment by cloudcant** [comment]
i found that editing the config area in Server.py on line 211 helps.
Just edit the path the server logs its sessions to and you should be able to access the web ui, also edit anythings else that may rely on the session files to the updated dir

```python
        conf = {
            '/':{
                'tools.staticdir.on': True,
                'tools.staticdir.dir': PATH,
                'tools.staticdir.index': 'login.html',
                'tools.sessions.on': True,
                'tools.sessions.storage_class' :cherrypy.lib.sessions.FileSession,
                'tools.sessions.storage_path' : PATH,
                'log.screen' : True,
                'tools.sessions.name': 'LoggedIn',
                'tools.auth_basic.checkpassword': Server().verify_login,
                }
            }
```
