### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by JanicePolito** [Mik317/PyBotnet#8]
Hi,

after changing paths in db.py and server.py i ran into http 500 error:

> 500 Internal Server Error
> The server encountered an unexpected condition which prevented it from fulfilling the request.
> 
> Traceback (most recent call last):
>   File "C:\Users\Mark\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\zc\lockfile\__init__.py", line 81, in __init__
>     fp = open(path, 'r+')
> FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Projects\\PyBotnet\\Server\\C&C\\sessions\\session-4ab13eb6e1a3fb8c5c34f1095488e858ab35ff0f.lock'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\Mark\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\cherrypy\_cprequest.py", line 638, in respond
>     self._do_respond(path_info)
>   File "C:\Users\Mark\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\cherrypy\_cprequest.py", line 694, in _do_respond
>     self.hooks.run('before_handler')
>   File "C:\Users\Mark\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\cherrypy\_cprequest.py", line 95, in run
>     self.run_hooks(iter(sorted(self[point])))
>   File "C:\Users\Mark\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\cherrypy\_cprequest.py", line 117, in run_hooks
>     hook()
>   File "C:\Users\Mark\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\cherrypy\_cprequest.py", line 65, in __call__
>     return self.callback(**self.kwargs)
>   File "C:\Users\Mark\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\cherrypy\_cptools.py", line 280, in _lock_session
>     cherrypy.serving.session.acquire_lock()
>   File "C:\Users\Mark\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\cherrypy\lib\sessions.py", line 556, in acquire_lock
>     self.lock = zc.lockfile.LockFile(path)
>   File "C:\Users\Mark\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\zc\lockfile\__init__.py", line 117, in __init__
>     super(LockFile, self).__init__(path)
>   File "C:\Users\Mark\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\zc\lockfile\__init__.py", line 87, in __init__
>     fp = open(path, 'a+')
> FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Projects\\PyBotnet\\Server\\C&C\\sessions\\session-4ab13eb6e1a3fb8c5c34f1095488e858ab35ff0f.lock'
> Powered by CherryPy 18.6.1

**Comment by JanicePolito** [comment]
Ok, managed to resolve the issue by creating an empty directory in Server\C&C\ path called 'sessions'
